channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=24.0
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - feature-engine==1.8.2
  - numpy==1.26.3
  - pandas==2.2.3
  - psutil==5.9.7
  - scikit-learn==1.4.0
  - scipy==1.11.4
name: mlflow-env
